name: Concurrency
on: push
concurrency:
 group: ${{ github.workflow }} # Concurrencyグループへワークフロー名を指定
 cancel-in-progress: true
jobs:
  sleep:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 119